"""
Model Registry — all supported models with hardware requirements and capabilities.
Updated with 2026 model strings verified against LiteLLM provider mappings.
"""

from typing import Any

MODEL_REGISTRY: list[dict[str, Any]] = [

    # ── Anthropic ─────────────────────────────────────────────────────────────
    {
        "id": "anthropic/claude-opus-4-5",
        "provider": "anthropic",
        "label": "Claude Opus 4.5",
        "category": "cloud",
        "context_k": 200,
        "tool_use": True,
        "reasoning": True,
        "strengths": ["best_reasoning", "ambiguity_resolution", "complex_tasks"],
        "cost_tier": "high",
        "recommended_for": ["reasoning"],
    },
    {
        "id": "anthropic/claude-sonnet-4-5",
        "provider": "anthropic",
        "label": "Claude Sonnet 4.5",
        "category": "cloud",
        "context_k": 200,
        "tool_use": True,
        "reasoning": True,
        "strengths": ["balanced", "tool_use", "fast"],
        "cost_tier": "medium",
        "recommended_for": ["reasoning", "write", "parsing"],
    },
    {
        "id": "anthropic/claude-haiku-4-5",
        "provider": "anthropic",
        "label": "Claude Haiku 4.5",
        "category": "cloud",
        "context_k": 200,
        "tool_use": True,
        "reasoning": False,
        "strengths": ["very_fast", "tool_use", "cheap"],
        "cost_tier": "low",
        "recommended_for": ["write", "validation", "orchestrator"],
    },

    # ── Google ────────────────────────────────────────────────────────────────
    {
        "id": "google/gemini-2.5-flash-preview-04-17",
        "provider": "google",
        "label": "Gemini 2.5 Flash",
        "category": "cloud",
        "context_k": 1000,
        "tool_use": True,
        "reasoning": True,
        "strengths": ["fast", "long_context", "multimodal", "cheap", "moe"],
        "cost_tier": "very_low",
        "recommended_for": ["orchestrator", "config_agent", "parsing", "intake"],
    },
    {
        "id": "google/gemini-2.5-pro-preview-06-05",
        "provider": "google",
        "label": "Gemini 2.5 Pro",
        "category": "cloud",
        "context_k": 1000,
        "tool_use": True,
        "reasoning": True,
        "strengths": ["top_tier", "long_context", "multimodal"],
        "cost_tier": "medium",
        "recommended_for": ["reasoning"],
    },
    {
        "id": "google/gemini-2.0-flash",
        "provider": "google",
        "label": "Gemini 2.0 Flash",
        "category": "cloud",
        "context_k": 1000,
        "tool_use": True,
        "reasoning": False,
        "strengths": ["very_fast", "cheap", "multimodal"],
        "cost_tier": "very_low",
        "recommended_for": ["intake", "context", "confidence", "validation"],
    },

    # ── Groq ──────────────────────────────────────────────────────────────────
    {
        "id": "groq/llama-3.3-70b-versatile",
        "provider": "groq",
        "label": "Llama 3.3 70B (Groq)",
        "category": "cloud",
        "context_k": 128,
        "tool_use": True,
        "reasoning": True,
        "strengths": ["very_fast_inference", "strong_extraction", "free_tier"],
        "cost_tier": "very_low",
        "recommended_for": ["parsing", "reasoning", "orchestrator"],
    },
    {
        "id": "groq/meta-llama/llama-4-scout-17b-16e-instruct",
        "provider": "groq",
        "label": "Llama 4 Scout 17B MoE (Groq)",
        "category": "cloud",
        "context_k": 128,
        "tool_use": True,
        "reasoning": True,
        "strengths": ["moe", "fast", "efficient"],
        "cost_tier": "very_low",
        "recommended_for": ["orchestrator", "parsing", "confidence"],
    },
    {
        "id": "groq/meta-llama/llama-4-maverick-17b-128e-instruct",
        "provider": "groq",
        "label": "Llama 4 Maverick 17B MoE (Groq)",
        "category": "cloud",
        "context_k": 256,
        "tool_use": True,
        "reasoning": True,
        "strengths": ["moe", "large_moe", "strong_reasoning"],
        "cost_tier": "low",
        "recommended_for": ["reasoning", "orchestrator"],
    },

    # ── DeepSeek ──────────────────────────────────────────────────────────────
    {
        "id": "deepseek/deepseek-chat",
        "provider": "deepseek",
        "label": "DeepSeek V3",
        "category": "cloud",
        "context_k": 64,
        "tool_use": True,
        "reasoning": True,
        "strengths": ["strong_reasoning", "very_cheap", "analytical", "moe"],
        "cost_tier": "very_low",
        "recommended_for": ["audit", "reasoning", "parsing"],
    },
    {
        "id": "deepseek/deepseek-reasoner",
        "provider": "deepseek",
        "label": "DeepSeek R1",
        "category": "cloud",
        "context_k": 64,
        "tool_use": False,
        "reasoning": True,
        "strengths": ["deep_reasoning", "chain_of_thought"],
        "cost_tier": "low",
        "recommended_for": ["reasoning"],
    },

    # ── Perplexity ────────────────────────────────────────────────────────────
    {
        "id": "perplexity/sonar-pro",
        "provider": "perplexity",
        "label": "Perplexity Sonar Pro",
        "category": "cloud",
        "context_k": 127,
        "tool_use": False,
        "reasoning": True,
        "web_search": True,
        "strengths": ["web_search", "real_time_info", "deep_research"],
        "cost_tier": "medium",
        "recommended_for": ["enrichment", "config_agent"],
    },
    {
        "id": "perplexity/sonar",
        "provider": "perplexity",
        "label": "Perplexity Sonar",
        "category": "cloud",
        "context_k": 127,
        "tool_use": False,
        "reasoning": False,
        "web_search": True,
        "strengths": ["web_search", "real_time_info", "cheap"],
        "cost_tier": "low",
        "recommended_for": ["enrichment"],
    },

    # ── Moonshot (Kimi) ───────────────────────────────────────────────────────
    {
        "id": "moonshot/kimi-k2-preview",
        "provider": "moonshot",
        "label": "Kimi K2 Preview",
        "category": "cloud",
        "context_k": 128,
        "tool_use": True,
        "reasoning": True,
        "strengths": ["moe", "strong_extraction", "multilingual", "long_context"],
        "cost_tier": "low",
        "recommended_for": ["reasoning", "parsing", "orchestrator"],
    },
    {
        "id": "openrouter/moonshotai/kimi-k2",
        "provider": "openrouter",
        "label": "Kimi K2 (OpenRouter)",
        "category": "cloud",
        "context_k": 128,
        "tool_use": True,
        "reasoning": True,
        "strengths": ["moe", "strong_extraction", "multilingual"],
        "cost_tier": "low",
        "recommended_for": ["reasoning", "parsing", "orchestrator"],
    },
    {
        "id": "openrouter/moonshotai/kimi-k2.5",
        "provider": "openrouter",
        "label": "Kimi K2.5 (OpenRouter)",
        "category": "cloud",
        "context_k": 128,
        "tool_use": True,
        "reasoning": True,
        "strengths": ["moe", "improved_k2", "multilingual"],
        "cost_tier": "low",
        "recommended_for": ["reasoning", "parsing"],
    },

    # ── Liquid AI (LFM) ───────────────────────────────────────────────────────
    {
        "id": "liquid/lfm2-24b-a2b",
        "provider": "liquid",
        "label": "LFM 2 24B MoE (Medium)",
        "category": "cloud",
        "context_k": 32,
        "tool_use": True,
        "reasoning": True,
        "strengths": ["moe", "efficient", "fast"],
        "cost_tier": "low",
        "recommended_for": ["orchestrator", "parsing", "confidence"],
    },
    {
        "id": "liquid/lfm2-8b-a1b",
        "provider": "liquid",
        "label": "LFM 2 8B MoE (Small)",
        "category": "cloud",
        "context_k": 32,
        "tool_use": False,
        "reasoning": False,
        "strengths": ["moe", "very_fast", "on_device"],
        "cost_tier": "very_low",
        "recommended_for": ["intake", "context", "validation"],
    },
    {
        "id": "liquid/lfm-2.5-1.2b-thinking",
        "provider": "liquid",
        "label": "LFM 2.5 1.2B Thinking (Draft)",
        "category": "cloud",
        "context_k": 32,
        "tool_use": False,
        "reasoning": True,
        "strengths": ["speculative_draft", "tiny", "fast"],
        "cost_tier": "very_low",
        "recommended_for": [],
        "draft_model": True,
    },
    {
        "id": "liquid/lfm-2.5-1.2b-instruct",
        "provider": "liquid",
        "label": "LFM 2.5 1.2B Instruct (Draft)",
        "category": "cloud",
        "context_k": 32,
        "tool_use": False,
        "reasoning": False,
        "strengths": ["speculative_draft", "tiny", "fastest"],
        "cost_tier": "very_low",
        "recommended_for": [],
        "draft_model": True,
    },

    # ── StepFun (Step) ────────────────────────────────────────────────────────
    {
        "id": "stepfun/step-3.5-flash",
        "provider": "stepfun",
        "label": "Step 3.5 Flash (196B MoE)",
        "category": "cloud",
        "context_k": 256,
        "tool_use": True,
        "reasoning": True,
        "strengths": ["massive_moe", "196b_sparse", "fast_routing", "openai_compatible"],
        "cost_tier": "low",
        "recommended_for": ["orchestrator", "reasoning", "parsing"],
    },
    {
        "id": "openrouter/stepfun/step-3.5-flash",
        "provider": "openrouter",
        "label": "Step 3.5 Flash (OpenRouter)",
        "category": "cloud",
        "context_k": 256,
        "tool_use": True,
        "reasoning": True,
        "strengths": ["massive_moe", "196b_sparse", "free_tier"],
        "cost_tier": "very_low",
        "recommended_for": ["orchestrator", "reasoning"],
    },

    # ── Qwen 3 (Alibaba via OpenRouter) ──────────────────────────────────────
    {
        "id": "openrouter/qwen/qwen3.6-plus",
        "provider": "openrouter",
        "label": "Qwen 3.6 Plus (MoE)",
        "category": "cloud",
        "context_k": 128,
        "tool_use": True,
        "reasoning": True,
        "strengths": ["moe", "strong_reasoning", "multilingual", "efficient"],
        "cost_tier": "low",
        "recommended_for": ["orchestrator", "reasoning", "parsing"],
    },

    # ── OpenAI ────────────────────────────────────────────────────────────────
    {
        "id": "openai/gpt-4o",
        "provider": "openai",
        "label": "GPT-4o",
        "category": "cloud",
        "context_k": 128,
        "tool_use": True,
        "reasoning": True,
        "strengths": ["multimodal", "tool_use", "balanced"],
        "cost_tier": "medium",
        "recommended_for": ["parsing", "reasoning", "write"],
    },
    {
        "id": "openai/gpt-4o-mini",
        "provider": "openai",
        "label": "GPT-4o Mini",
        "category": "cloud",
        "context_k": 128,
        "tool_use": True,
        "reasoning": False,
        "strengths": ["fast", "cheap", "tool_use"],
        "cost_tier": "very_low",
        "recommended_for": ["validation", "confidence", "write"],
    },

    # ── Local: Ollama ─────────────────────────────────────────────────────────
    {
        "id": "ollama/gemma3:4b",
        "provider": "ollama",
        "label": "Gemma 3 4B (Local)",
        "category": "local",
        "context_k": 128,
        "tool_use": False,
        "reasoning": False,
        "strengths": ["very_fast_local", "low_vram"],
        "cost_tier": "free",
        "vram_required_gb": 3.0,
        "ram_required_gb": 6.0,
        "recommended_for": ["intake", "context", "confidence", "validation", "hitl", "learning"],
    },
    {
        "id": "ollama/gemma3:12b",
        "provider": "ollama",
        "label": "Gemma 3 12B (Local)",
        "category": "local",
        "context_k": 128,
        "tool_use": False,
        "reasoning": True,
        "strengths": ["capable_local", "medium_vram"],
        "cost_tier": "free",
        "vram_required_gb": 8.0,
        "ram_required_gb": 16.0,
        "recommended_for": ["parsing", "context", "audit", "orchestrator"],
    },
    {
        "id": "ollama/gemma3:27b",
        "provider": "ollama",
        "label": "Gemma 3 27B (Local)",
        "category": "local",
        "context_k": 128,
        "tool_use": False,
        "reasoning": True,
        "strengths": ["strong_local", "high_vram"],
        "cost_tier": "free",
        "vram_required_gb": 16.0,
        "ram_required_gb": 32.0,
        "recommended_for": ["reasoning", "parsing", "orchestrator"],
    },
    {
        "id": "ollama/gemma4:e4b",
        "provider": "ollama",
        "label": "Gemma 4 E4B MoE (Local)",
        "category": "local",
        "context_k": 128,
        "tool_use": False,
        "reasoning": True,
        "strengths": ["moe_local", "efficient", "medium_vram"],
        "cost_tier": "free",
        "vram_required_gb": 6.0,
        "ram_required_gb": 12.0,
        "recommended_for": ["orchestrator", "parsing", "confidence"],
    },
    {
        "id": "ollama/gemma4:e2b",
        "provider": "ollama",
        "label": "Gemma 4 E2B MoE (Draft/Local)",
        "category": "local",
        "context_k": 32,
        "tool_use": False,
        "reasoning": False,
        "strengths": ["speculative_draft", "ultra_fast_local", "tiny_vram"],
        "cost_tier": "free",
        "vram_required_gb": 2.0,
        "ram_required_gb": 4.0,
        "recommended_for": [],
        "draft_model": True,
    },
    {
        "id": "ollama/llama3.3:70b",
        "provider": "ollama",
        "label": "Llama 3.3 70B (Local)",
        "category": "local",
        "context_k": 128,
        "tool_use": True,
        "reasoning": True,
        "strengths": ["most_capable_local", "tool_use"],
        "cost_tier": "free",
        "vram_required_gb": 40.0,
        "ram_required_gb": 64.0,
        "recommended_for": ["reasoning", "parsing", "write"],
    },
    {
        "id": "ollama/lfm2.5:1.2b",
        "provider": "ollama",
        "label": "LFM 2.5 1.2B (Draft/Local)",
        "category": "local",
        "context_k": 32,
        "tool_use": False,
        "reasoning": False,
        "strengths": ["speculative_draft", "minimal_vram", "fastest_local"],
        "cost_tier": "free",
        "vram_required_gb": 1.5,
        "ram_required_gb": 3.0,
        "recommended_for": [],
        "draft_model": True,
    },
    {
        "id": "ollama/qwen2.5:7b",
        "provider": "ollama",
        "label": "Qwen 2.5 7B (Local)",
        "category": "local",
        "context_k": 32,
        "tool_use": True,
        "reasoning": False,
        "strengths": ["fast_local", "tool_use", "multilingual"],
        "cost_tier": "free",
        "vram_required_gb": 6.0,
        "ram_required_gb": 12.0,
        "recommended_for": ["parsing", "validation", "write"],
    },
    {
        "id": "ollama/qwen2.5:14b",
        "provider": "ollama",
        "label": "Qwen 2.5 14B (Local)",
        "category": "local",
        "context_k": 32,
        "tool_use": True,
        "reasoning": True,
        "strengths": ["balanced_local", "tool_use"],
        "cost_tier": "free",
        "vram_required_gb": 10.0,
        "ram_required_gb": 20.0,
        "recommended_for": ["parsing", "reasoning", "write"],
    },
    {
        "id": "ollama/mistral:7b",
        "provider": "ollama",
        "label": "Mistral 7B (Local)",
        "category": "local",
        "context_k": 32,
        "tool_use": False,
        "reasoning": False,
        "strengths": ["fast_local", "instruction_following"],
        "cost_tier": "free",
        "vram_required_gb": 6.0,
        "ram_required_gb": 12.0,
        "recommended_for": ["intake", "validation"],
    },
    {
        "id": "ollama/phi4",
        "provider": "ollama",
        "label": "Phi-4 (Local)",
        "category": "local",
        "context_k": 16,
        "tool_use": False,
        "reasoning": True,
        "strengths": ["strong_reasoning_small", "efficient"],
        "cost_tier": "free",
        "vram_required_gb": 10.0,
        "ram_required_gb": 16.0,
        "recommended_for": ["confidence", "validation", "reasoning"],
    },
]


def get_registry() -> list[dict]:
    return MODEL_REGISTRY


def get_models_for_agent(agent_name: str) -> list[dict]:
    return [m for m in MODEL_REGISTRY if agent_name in m.get("recommended_for", [])]


def get_compatible_local_models(vram_gb: float, ram_gb: float) -> list[dict]:
    compatible = []
    for m in MODEL_REGISTRY:
        if m["category"] != "local":
            continue
        if vram_gb >= 2.0:
            if vram_gb >= m.get("vram_required_gb", 999):
                compatible.append(m)
        else:
            if ram_gb >= m.get("ram_required_gb", 999):
                compatible.append(m)
    return compatible
